### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by klamping** [jamischarles/hydra#1]
Do you know what this is?
- I think I get the basic idea of it. A way to help developers get started with learning a new skill/set of skills.

Are you interested in using it? 
- Right now, I think the 'new developer' niche has a lot of options via other sources (codecademy, treehouse, etc). So before using it, I'd like to know how it differs from those other resources.

Interested in collaborating?
- I'll actually be doing a UI regression testing workshop in October for a conference and want to make it re-usable outside of that. I could frame it all in the template you've provided and see how it works.
- I also wrote up a "course" on TDD for JS that could be copied over pretty easily (http://learntestdrivenjavascript.com)

What is missing?
- Mainly, a fully realized skillset. This will help show off how it should all look from a whole.

What is confusing?
- How are assignments completed? Are they "graded" in any way?
- How is progress tracked?

3 things you'd improve immediately (or 3 things that are missing)?
- Focus on more advanced courses like TDD and benchmarking
- Define how progress will be viewed/tracked

**Comment by jamischarles** [comment]
This is great. Thanks. Will respond throughout the day as I think of things to say.

**Comment by jamischarles** [comment]
I tried to address all your feedback. Can you take another look and share your thoughts again? https://github.com/jamischarles/hydra

**Comment by klamping** [comment]
hey, i do have this on my backlog of things to do and will get you a response within the next week!

**Comment by klamping** [comment]
I like all the issues you've opened up, especially how many of them are focused on a single topic (e.g. https://github.com/jamischarles/hydra/issues/13). 

I think the soft skills lessons are also a great thing to develop out. Usually something that gets overlooked in training courses, but can provide a huge benefit to productivity.
